## Description: Download metadata for SCORES from the Google Spreadsheet.
##              Update the SID variable below when the deployment of the
##              Google Apps Script has changed.
##
##              Type "make" in this directory to download the JSON files for the metadata.
##

SID = AKfycbw3C-1VEObsDfzPGKLOSY2GynDVWpuKlLpQfCDs-vjAwl_4JOF5Br_ysu7jpKH7Ga4zDA

all: download

download: works

works:
	curl -L "https://script.google.com/macros/s/$(SID)/exec?sheet=works" > works.json





